import { RatePlan, User, UserCustomRule, RedisKeyItem, RedisStats, SystemStats, ActivityLog } from '@/types';

export const INITIAL_PLANS: RatePlan[] = [
  {
    id: 'plan-1',
    name: 'Free Tier',
    code: 'FREE',
    description: 'Entry level plan for hobby projects and evaluation.',
    maxRequests: 5,
    windowValue: 1,
    windowUnit: 'MINUTE',
    isDefault: true,
    userCount: 142,
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'plan-2',
    name: 'Standard Developer',
    code: 'BASIC',
    description: 'Suitable for small production apps and growing APIs.',
    maxRequests: 20,
    windowValue: 1,
    windowUnit: 'MINUTE',
    isDefault: false,
    userCount: 89,
    createdAt: '2026-01-15T08:30:00Z',
  },
  {
    id: 'plan-3',
    name: 'Professional',
    code: 'PRO',
    description: 'High performance rate limits for scaling businesses.',
    maxRequests: 50,
    windowValue: 1,
    windowUnit: 'MINUTE',
    isDefault: false,
    userCount: 45,
    createdAt: '2026-01-16T10:00:00Z',
  },
  {
    id: 'plan-4',
    name: 'Enterprise Scale',
    code: 'ENTERPRISE',
    description: 'Dedicated limits for high-volume enterprise workloads.',
    maxRequests: 100,
    windowValue: 1,
    windowUnit: 'MINUTE',
    isDefault: false,
    userCount: 12,
    createdAt: '2026-01-20T12:00:00Z',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-101',
    clientId: 'C-001',
    clientName: 'Acme Global Corp',
    email: 'api-admin@acme.com',
    planId: 'plan-4',
    planName: 'Enterprise Scale',
    customRuleEnabled: true,
    status: 'ACTIVE',
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'usr-102',
    clientId: 'C-002',
    clientName: 'TechFlow Solutions',
    email: 'dev@techflow.io',
    planId: 'plan-3',
    planName: 'Professional',
    customRuleEnabled: false,
    status: 'ACTIVE',
    createdAt: '2026-02-03T11:20:00Z',
  },
  {
    id: 'usr-103',
    clientId: 'C-003',
    clientName: 'DevStudio LLC',
    email: 'support@devstudio.dev',
    planId: 'plan-2',
    planName: 'Standard Developer',
    customRuleEnabled: false,
    status: 'ACTIVE',
    createdAt: '2026-02-05T14:15:00Z',
  },
  {
    id: 'usr-104',
    clientId: 'C-004',
    clientName: 'Hobbyist App',
    email: 'user@hobby.net',
    planId: 'plan-1',
    planName: 'Free Tier',
    customRuleEnabled: false,
    status: 'ACTIVE',
    createdAt: '2026-02-07T09:40:00Z',
  },
  {
    id: 'usr-105',
    clientId: 'C-005',
    clientName: 'Global Logistics API',
    email: 'ops@globallogistics.com',
    planId: 'plan-4',
    planName: 'Enterprise Scale',
    customRuleEnabled: true,
    status: 'ACTIVE',
    createdAt: '2026-02-10T16:00:00Z',
  },
  {
    id: 'usr-106',
    clientId: 'C-006',
    clientName: 'FinTech Secure Gateway',
    email: 'security@fintechpay.com',
    planId: 'plan-4',
    planName: 'Enterprise Scale',
    customRuleEnabled: true,
    status: 'ACTIVE',
    createdAt: '2026-02-12T08:10:00Z',
  },
  {
    id: 'usr-107',
    clientId: 'C-007',
    clientName: 'Nexus AI Systems',
    email: 'api@nexusai.tech',
    planId: 'plan-3',
    planName: 'Professional',
    customRuleEnabled: false,
    status: 'ACTIVE',
    createdAt: '2026-02-14T13:45:00Z',
  },
  {
    id: 'usr-108',
    clientId: 'C-008',
    clientName: 'Cloud Metrics Inc',
    email: 'telemetry@cloudmetrics.org',
    planId: 'plan-2',
    planName: 'Standard Developer',
    customRuleEnabled: false,
    status: 'SUSPENDED',
    createdAt: '2026-02-15T17:30:00Z',
  },
];

export const INITIAL_CUSTOM_RULES: UserCustomRule[] = [
  {
    id: 'rule-001',
    clientId: 'C-001',
    clientName: 'Acme Global Corp',
    maxRequests: 250,
    windowValue: 1,
    windowUnit: 'MINUTE',
    enabled: true,
    reason: 'VIP SLA Contract - Q1 High Volume Override',
    updatedAt: '2026-02-18T10:30:00Z',
  },
  {
    id: 'rule-005',
    clientId: 'C-005',
    clientName: 'Global Logistics API',
    maxRequests: 1000,
    windowValue: 1,
    windowUnit: 'HOUR',
    enabled: true,
    reason: 'Batch sync integration allowance',
    updatedAt: '2026-02-20T15:10:00Z',
  },
  {
    id: 'rule-006',
    clientId: 'C-006',
    clientName: 'FinTech Secure Gateway',
    maxRequests: 300,
    windowValue: 1,
    windowUnit: 'MINUTE',
    enabled: true,
    reason: 'High frequency payment webhook processing',
    updatedAt: '2026-02-22T09:00:00Z',
  },
];

export const INITIAL_REDIS_KEYS: RedisKeyItem[] = [
  // Rate Limit Counter Keys
  {
    key: 'rate_limit:C-001',
    type: 'rate_limit',
    clientId: 'C-001',
    ttlSeconds: 42,
    currentCount: 184,
    maxRequests: 250,
    windowValue: 1,
    windowUnit: 'MINUTE',
    status: 'ALLOWED',
    lastUpdated: new Date().toISOString(),
  },
  {
    key: 'rate_limit:C-002',
    type: 'rate_limit',
    clientId: 'C-002',
    ttlSeconds: 15,
    currentCount: 48,
    maxRequests: 50,
    windowValue: 1,
    windowUnit: 'MINUTE',
    status: 'WARNING',
    lastUpdated: new Date().toISOString(),
  },
  {
    key: 'rate_limit:C-004',
    type: 'rate_limit',
    clientId: 'C-004',
    ttlSeconds: 28,
    currentCount: 5,
    maxRequests: 5,
    windowValue: 1,
    windowUnit: 'MINUTE',
    status: 'THROTTLED',
    lastUpdated: new Date().toISOString(),
  },
  {
    key: 'rate_limit:C-006',
    type: 'rate_limit',
    clientId: 'C-006',
    ttlSeconds: 51,
    currentCount: 120,
    maxRequests: 300,
    windowValue: 1,
    windowUnit: 'MINUTE',
    status: 'ALLOWED',
    lastUpdated: new Date().toISOString(),
  },

  // Rule Cache Keys
  {
    key: 'rate_rule:C-001',
    type: 'rate_rule',
    clientId: 'C-001',
    ttlSeconds: 3450,
    maxRequests: 250,
    windowValue: 1,
    windowUnit: 'MINUTE',
    source: 'CUSTOM_RULE',
    lastUpdated: new Date().toISOString(),
  },
  {
    key: 'rate_rule:C-002',
    type: 'rate_rule',
    clientId: 'C-002',
    ttlSeconds: 3580,
    maxRequests: 50,
    windowValue: 1,
    windowUnit: 'MINUTE',
    source: 'RATE_PLAN',
    lastUpdated: new Date().toISOString(),
  },
  {
    key: 'rate_rule:C-003',
    type: 'rate_rule',
    clientId: 'C-003',
    ttlSeconds: 1200,
    maxRequests: 20,
    windowValue: 1,
    windowUnit: 'MINUTE',
    source: 'RATE_PLAN',
    lastUpdated: new Date().toISOString(),
  },
  {
    key: 'rate_rule:C-004',
    type: 'rate_rule',
    clientId: 'C-004',
    ttlSeconds: 2900,
    maxRequests: 5,
    windowValue: 1,
    windowUnit: 'MINUTE',
    source: 'RATE_PLAN',
    lastUpdated: new Date().toISOString(),
  },
  {
    key: 'rate_rule:C-005',
    type: 'rate_rule',
    clientId: 'C-005',
    ttlSeconds: 3600,
    maxRequests: 1000,
    windowValue: 1,
    windowUnit: 'HOUR',
    source: 'CUSTOM_RULE',
    lastUpdated: new Date().toISOString(),
  },
  {
    key: 'rate_rule:C-006',
    type: 'rate_rule',
    clientId: 'C-006',
    ttlSeconds: 3200,
    maxRequests: 300,
    windowValue: 1,
    windowUnit: 'MINUTE',
    source: 'CUSTOM_RULE',
    lastUpdated: new Date().toISOString(),
  },
];

export const INITIAL_REDIS_STATS: RedisStats = {
  connected: true,
  version: '7.2.4-standalone',
  uptimeInSeconds: 124800,
  usedMemoryHuman: '14.8 MB',
  totalKeys: 288,
  rateLimitKeysCount: 142,
  ruleCacheKeysCount: 146,
  cacheHitRatio: 99.4,
  totalEvaluations: 1284500,
  blockedRequestsCount: 3412,
};

export const INITIAL_SYSTEM_STATS: SystemStats = {
  totalUsers: 288,
  activeUsers: 280,
  activePlans: 4,
  customRulesCount: 3,
  redisKeysCount: 288,
  totalRequests24h: 1284500,
  blockedRequests24h: 3412,
  averageResponseTimeMs: 1.8,
};

export const INITIAL_LOGS: ActivityLog[] = [
  {
    id: 'log-1',
    timestamp: new Date(Date.now() - 1000 * 30).toISOString(),
    clientId: 'C-004',
    clientName: 'Hobbyist App',
    action: 'BLOCKED',
    details: 'Rate limit exceeded: 6th request in 1 minute window (Max: 5 req/min). HTTP 429 returned.',
    status: 'DANGER',
  },
  {
    id: 'log-2',
    timestamp: new Date(Date.now() - 1000 * 120).toISOString(),
    clientId: 'C-001',
    clientName: 'Acme Global Corp',
    action: 'EVALUATED',
    details: 'Rate limit check passed: Count 184/250 (Custom Rule: 250 req/min).',
    status: 'SUCCESS',
  },
  {
    id: 'log-3',
    timestamp: new Date(Date.now() - 1000 * 300).toISOString(),
    clientId: 'C-002',
    clientName: 'TechFlow Solutions',
    action: 'CACHE_HIT',
    details: 'Fetched rate_rule:C-002 from Redis cache (PRO plan rule: 50 req/min).',
    status: 'INFO',
  },
  {
    id: 'log-4',
    timestamp: new Date(Date.now() - 1000 * 600).toISOString(),
    clientId: 'C-006',
    clientName: 'FinTech Secure Gateway',
    action: 'RULE_UPDATED',
    details: 'Updated UserCustomRule: maxRequests set to 300 req/min. Evicted cache rate_rule:C-006.',
    status: 'WARNING',
  },
  {
    id: 'log-5',
    timestamp: new Date(Date.now() - 1000 * 900).toISOString(),
    clientId: 'C-008',
    clientName: 'Cloud Metrics Inc',
    action: 'CACHE_MISS',
    details: 'Cache miss for rate_rule:C-008. Loaded rule from DB and cached into Redis with TTL 3600s.',
    status: 'INFO',
  },
];
